site_name: mq
repo_url: https://github.com/mamori-tai/mq
repo_name: mq
theme:
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.expand
    - navigation.indexes
    - toc.integrate

  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
nav:
  - Tutorial: index.md
  - enqueuing.md
  - dequeuing.md
  - api:
      - api/index.md

plugins:
  - search
  - mkdocstrings